<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://www.oracle.com/PartyObject/V0"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/PartyEventsDbAdapter"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/EmployeeApp/PublishMultiXMLtest/EventsBPELProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pf="http://www.oracle.com/PartyFinance/V0"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/EmployeeApp/PublishMultiXMLtest/PartyEventsDbAdapter"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EventsBPELProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PartyEvent" namespace="http://www.oracle.com/PartyObject/V0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PartyEventsDbAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PartyeventsCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PartyEventsDbAdapter"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON NOV 16 01:01:22 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:PartyeventsCollection>
      <tns:Partyevents>
        <tns:prtyName>
          <xsl:value-of select="/ns0:PartyEvent/ns0:PartyEventStructure/ns0:PartyDetails/ns0:PartyName"/>
        </tns:prtyName>
        <tns:custNumr>
          <xsl:value-of select="/ns0:PartyEvent/ns0:PartyEventStructure/ns0:PartyDetails/ns0:CustomerNumber"/>
        </tns:custNumr>
        <tns:prtyAddr>
          <xsl:value-of select="/ns0:PartyEvent/ns0:PartyEventStructure/ns0:PartyDetails/ns0:PartyAddress"/>
        </tns:prtyAddr>
        <tns:eventType>
          <xsl:value-of select="/ns0:PartyEvent/ns0:PartyEventStructure/ns0:EventDetails/ns0:Event"/>
        </tns:eventType>
        <tns:eventDate>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:eventDate>
      </tns:Partyevents>
    </tns:PartyeventsCollection>
  </xsl:template>
</xsl:stylesheet>
