<wsdl:definitions
     name="PartyEventDbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EmployeeApp/PublisherXMLTest/PartyEventDbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EmployeeApp/PublisherXMLTest/PartyEventDbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PartyEventDbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PartyEventDbReference_plt" >
    <plt:role name="PartyEventDbReference_role" >
      <plt:portType name="tns:PartyEventDbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PartyEventDbReference" schemaLocation="../Schemas/PartyEventDbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PartyeventsCollection_msg">
        <wsdl:part name="PartyeventsCollection" element="top:PartyeventsCollection"/>
    </wsdl:message>
    <wsdl:portType name="PartyEventDbReference_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PartyeventsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
