<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://www.oracle.com/TestSchema/V0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://www.oracle.com/PartyEventPublish/V0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/EmployeeApp/PublishXMLToTopic/PartyEventJMSAdapter"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/jms/EmployeeApp/PublishXMLToTopic/PartyEventPublishJMSAdapter">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PartyEventJMSAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PartyObject" namespace="http://www.oracle.com/TestSchema/V0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PartyEventPublishJMSAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Partyevents" namespace="http://www.oracle.com/PartyEventPublish/V0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE NOV 17 23:55:31 CET 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Partyevents>
      <tns:Partyevents>
        <tns:prtyName>
          <xsl:value-of select="/ns0:PartyObject/ns0:PartyDetails/ns0:PartyName"/>
        </tns:prtyName>
        <tns:custNumr>
          <xsl:value-of select="/ns0:PartyObject/ns0:PartyDetails/ns0:CustomerNumber"/>
        </tns:custNumr>
        <tns:prtyAddr>
          <xsl:value-of select="/ns0:PartyObject/ns0:PartyDetails/ns0:PartyAddress"/>
        </tns:prtyAddr>
        <tns:eventType>
          <xsl:value-of select="/ns0:PartyObject/ns0:EventDetails/ns0:Event"/>
        </tns:eventType>
        <tns:eventDate>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:eventDate>
      </tns:Partyevents>
    </tns:Partyevents>
  </xsl:template>
</xsl:stylesheet>
