<wsdl:definitions
     name="EmployeeConsumer"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EmployeeApp/EmployeeMain/EmployeeConsumer"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EmployeeApp/EmployeeMain/EmployeeConsumer"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EmployeeConsumer"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EmployeeConsumer_plt" >
    <plt:role name="EmployeeConsumer_role" >
      <plt:portType name="tns:EmployeeConsumer_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EmployeeConsumer" schemaLocation="../Schemas/EmployeeConsumer_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmployeeCollection_msg">
        <wsdl:part name="EmployeeCollection" element="top:EmployeeCollection"/>
    </wsdl:message>
    <wsdl:portType name="EmployeeConsumer_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EmployeeCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
